#!/bin/bash
LOG_FILE="/home/ec2-user/nft-backend/deploy.log"
echo 'cd /home/ec2-user Checking' >> "$LOG_FILE"
cd /home/ec2-user >> "$LOG_FILE"
whoami >> "$LOG_FILE"
export PATH="/usr/bin:/usr/local/bin:/usr/bin/git:/bin/git:$PATH"
echo $PATH >> "$LOG_FILE"
cd /home/ec2-user/nft-backend >> "$LOG_FILE"
pwd >> "$LOG_FILE"
git fetch >> "$LOG_FILE"
git checkout dev-release >> "$LOG_FILE"
echo 'it checkout dev-release----' >> "$LOG_FILE"
git reset --hard origin/dev-release >> "$LOG_FILE"
echo 'git reset --hard origin/dev-release----' >> "$LOG_FILE"
git status >> "$LOG_FILE"
echo 'git status----' >> "$LOG_FILE"
git fetch >> "$LOG_FILE"
git pull >> "$LOG_FILE"
git show --summary >> "$LOG_FILE"
npm install >> "$LOG_FILE"
